name: graphql_test_pos
description: graphql_test_pos
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  gql_dio_link: ^0.2.2
  gql_link: ^0.4.2
  json_annotation: ^4.6.0
  meta: ^1.8.0

dev_dependencies:
  artemis: ^7.9.0-beta
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.2


flutter:
  uses-material-design: true
